Fix logout URL for France Connect V2
InseeFr/Keycloak-FranceConnect pull request #63
Opened 2021-11-25 08:20 UTC by micedre

Fix url

2021-12-08 16:14 UTC, mboisnard requested changes

2021-12-08 16:14 UTC, mboisnard commented on src/main/java/fr/insee/keycloak/providers/common/AbstractBaseIdentityProvider.java
> +  public abstract String getIdTokenForLogout(UserSessionModel userSession);
I think you can have the default behavior here:

```
protected String getIdTokenForLogout(UserSessionModel userSession) {
     return userSession.getNote(FEDERATED_ID_TOKEN);
}
```

2021-12-08 16:14 UTC, mboisnard commented on src/main/java/fr/insee/keycloak/providers/franceconnect/FranceConnectIdentityProvider.java
> +      var idToken = userSession.getNote(FEDERATED_ID_TOKEN);
And `var idToken = super(userSession);` here.

2021-12-13 06:00 UTC, micedre commented
you're right, thanks. I'll wait for an answer from FC on the reason to pass decrypted token here before marking that PR as ready again.

2022-01-03 08:57 UTC, micedre commented
No response from FC, I'll merge this, to make a new release

2022-01-04 08:36 UTC, merged